### ISSUE TITLE
Using @extends descriptor to state class inheritance from another class wrapped in <p></p>

### ISSUE THREAD

**Issue by rjburney** [yui/yuidoc#332] opened 2015-03-24 17:47 UTC
![image](https://cloud.githubusercontent.com/assets/11635025/6808723/06239bce-d22c-11e4-81eb-518023f3f47a.png)

**Comment by okuryu** [comment] 2015-03-25 13:03
It's a duplicate of #324.

**Closed by okuryu** 2015-03-25 13:03 UTC
