### ISSUE TITLE
Possible conflict with classes of same name but different namespace

### ISSUE THREAD

**Issue by rvangundy** [yui/yuidoc#149] opened 2013-04-07 06:33 UTC
I have a different Base class in one of my submodules that inherits from my primary Base class.  One is just Base, the other is canvas.Base.  Here is my doc block for Base:

    /**
     * @class Base
     * @constructor
     */

And my canvas.Base:

    /**
     * @class canvas.Base
     * @module canvas
     * @namespace canvas
     * @extends events.EventTarget
     * @constructor
     */

In my documentation, the Base class is missing.  Also note that my Base.js file is in the root of my source (./src) while CanvasBase.js is in a canvas subfolder.

Perhaps related, but maybe a different issue altogether, is that some classes are listed under incorrect modules in the generated documentation.  I can fix this by placing the @module specifier as I did in the canvas.Base block, although I don't recall this being a documented use for @module.  Before @module was there, canvas.Base was listed as a class under my top-level module where I'd expect to find Base.

**Comment by kucukkanat** [comment] 2015-01-21 19:25
I have the same issue. For instance I have classes
@class loginControllers
@namespace core

@class loginControllers
@namespace Application

And under Application.loginControllers I see two login methods. The conflict. Is this an issue or bug or am I doing sth/ wrong?

**Comment by okuryu** [comment] 2015-01-22 13:23
@kucukkanat Are you using the latest version (v0.5.0)? I'm not able to reproduce it with following example. It seems to works fine for me.
`index1.js`:
```
/**
 * @namespace core
 * @class loginControllers
 */

/**
 * @method method1
 */
```
`index2.js`:
```
/**
 * @namespace Application
 * @class loginControllers
 */

/**
 * @method method2
 */
```

**Comment by okuryu** [comment] 2015-02-23 12:20
Closing, please let me know if you still have a same issue.

**Closed by okuryu** 2015-02-23 12:20 UTC
