### ISSUE TITLE
Issues with theming

### ISSUE THREAD

**Issue by Robdel12** [yui/yuidoc#320] opened 2015-02-27 17:26 UTC
I can't for the life of me get _any_ other theme than `default` to work. Even if I try to use `simple` I get a ton of console errors when loading the page:

![screen shot 2015-02-27 at 12 22 51 pm](https://cloud.githubusercontent.com/assets/2072894/6417470/930c4316-be7b-11e4-9764-be913fe6a95e.png)

I couldn't get it to work from the command line, server (yuidoc.json && as arguments in the command), and a gulp plugin. Just simply changing [this line](https://github.com/Robdel12/gulp-yuidoc/blob/master/index.js#L74) from `default` to `simple` doesn't compile the doc theme correctly. 

Any ideas? I can provide any information needed.

**Comment by okuryu** [comment] 2015-02-28 09:19
I cannot reproduce the above errors. Could you provide a reproduce example?

**Comment by Robdel12** [comment] 2015-02-28 18:23
Hmm! Okay. I wonder if this is an issue with my set up? Would you mind forking the project and attempting to build the docs? 


If so here are the steps:

- [Fork DropKick](https://github.com/Robdel12/DropKick)
- [Checkout the docs branch](https://github.com/Robdel12/DropKick/tree/add-doc-generator)
- run `npm install`
- After that run `gulp docs` to build the current docs with the default theme. 
- This is the hackyish part. Go into `node-modules` and find `gulp-yui-doc-relative`. Then go into the `index.js` and change [this line](https://github.com/Robdel12/gulp-yuidoc/blob/master/index.js#L74) to "simple" and try rebuilding the docs. For me this causes the screen shot above. 

If it works for you I'll be relieved :P

**Comment by okuryu** [comment] 2015-03-01 07:18
Thanks for details! I just verified to reproduce your problem.

It seems to due to `gulp-yuidoc` (and `gulp-yuidoc-relative`) directly calls `renderIndex()` API of YUIDoc Builder.

* https://github.com/jsBoot/gulp-yuidoc/blob/master/index.js#L73
* https://github.com/jsBoot/gulp-yuidoc/blob/master/lib/generator.js#L21
* https://github.com/jsBoot/gulp-yuidoc/blob/master/lib/generator.js#L74

The `renderIndex()` method actually works with preparing `default` and other themes. It means you need to pass the `themedir` option if you want to use any theme other than `default` theme.

* https://github.com/yui/yuidoc/blob/93038c43b6d71c121544ed22160e98cf7f84af15/lib/builder.js#L858

There are two workaround for this.

##### 1. Specify a `themedir` option to the `gulp-yuidoc` Generator

```diff
diff --git a/gulpfile.js b/gulpfile.js
index 93f1863..b5b87cb 100644
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -48,6 +48,8 @@ gulp.task('docs', function() {
       "version": "2.1.3",
       "url": "http://dropkickjs.com/"
     }
+  }, {
+    "themedir": "./node_modules/gulp-yuidoc-relative/node_modules/yuidocjs/themes/simple"
   })).pipe(gulp.dest("./docs"));
 });
```

##### 2. Use `yuidocjs` simply

AFAIK, `gulp-yuidoc` and `gulp-jsdoc` aren't actively maintained for now. This is an alternative way.

```sh
$ npm install --save-dev yuidocjs
```

Update the `yuidoc.json`.

```diff
diff --git a/yuidoc.json b/yuidoc.json
index d4e8500..c8a8d3a 100644
--- a/yuidoc.json
+++ b/yuidoc.json
@@ -4,6 +4,7 @@
   "version": "2.1.3",
   "url": "http://dropkickjs.com/",
   "options": {
-    "outdir": "docs"
+    "outdir": "docs",
+    "exclude": "tests"
   }
 }
```

Make a npm script in the `package.json`.

```js
  "scripts": {
    "docs": "yuidoc -T simple ."
  }
```

Running the npm script.

```sh
$ npm run docs
```

**Comment by Robdel12** [comment] 2015-03-02 13:30
Awesome!! I'l have to give this a shot. Thank you!

**Comment by okuryu** [comment] 2015-04-09 12:17
Closing, this isn't a bug on YUIDoc actually. Please let me know if you have any problems on this.

**Closed by okuryu** 2015-04-09 12:17 UTC

**Comment by Robdel12** [comment] 2015-04-09 23:24
Heh, yeah I thought it was already closed! Sorry about that. 

While I have your attention could you help me with this? http://stackoverflow.com/questions/29549851/how-to-replace-yuidocs-index-partial-with-the-classes-partial
